name: "Grype Scan: Golang"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  security-events: write

env:
  CLEAN_BRANCH_NAME: "main"

jobs:
  grype-scan:
    name: "Grype Scan"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clean branch name
        run: |
          echo "${GITHUB_REF_NAME}"
          CLEAN_BRANCH_NAME="${GITHUB_REF_NAME//\//-}"
          echo "CLEAN_BRANCH_NAME=$CLEAN_BRANCH_NAME" >> $GITHUB_ENV

      - name: "Generate CycloneDX"
        uses: anchore/sbom-action@v0
        with:
          path: "./golang"
          output-file: "./golang/${{ env.CLEAN_BRANCH_NAME }}-grype-cyclonedx.json"
          format: "cyclonedx-json"
          artifact-name: "${{ env.CLEAN_BRANCH_NAME }}-grype-cyclonedx.json"

      - name: "Generate SPDX"
        uses: anchore/sbom-action@v0
        with:
          path: "./golang"
          output-file: "./golang/${{ env.CLEAN_BRANCH_NAME }}-grype-spdx.json"
          format: "spdx-json"
          artifact-name: "${{ env.CLEAN_BRANCH_NAME }}-grype-spdx.json"

      - name: Scan
        id: scan_result
        uses: anchore/scan-action@v6
        continue-on-error: true
        with:
          sbom: "./golang/${{ env.CLEAN_BRANCH_NAME }}-grype-cyclonedx.json"
          fail-build: true
          severity-cutoff: low
          output-format: sarif
          output-file: "./golang/${{ env.CLEAN_BRANCH_NAME }}-grype.sarif"
          by-cve: true

      - name: Upload to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: "${{ steps.scan_result.outputs.sarif }}"
          checkout_path: "./golang/"

      - name: Print directory
        run: |
          echo "Print directory"
          tree ./golang

      - name: Fail on any vulnerabilities
        if: steps.scan_result.outcome == 'failure'
        run: |
          echo "Vulnerabilities detected!"
          exit 1
