name: "Grype Scan: Golang"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  security-events: write

env:
  TOOL: "grype"
  PROJECT_DIR: "golang"

jobs:
  grype-scan:
    name: "Grype Scan"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Generate CycloneDX"
        uses: anchore/sbom-action@v0
        with:
          path: "./golang"
          output-file: "./golang/grype-cyclonedx.json"
          format: "cyclonedx-json"
          artifact-name: "grype-cyclonedx.json"

      - name: "Generate SPDX"
        uses: anchore/sbom-action@v0
        with:
          path: "./golang"
          output-file: "./golang/grype-spdx.json"
          format: "spdx-json"
          artifact-name: "grype-spdx.json"

      - name: Scan
        id: ScanSarifResult
        uses: anchore/scan-action@v6
        continue-on-error: true
        with:
          sbom: "./golang/grype-cyclonedx.json"
          fail-build: true
          severity-cutoff: low
          output-format: sarif
          output-file: "./golang/grype.sarif"
          by-cve: true

      - name: Upload to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: "${{ steps.ScanSarifResult.outputs.sarif }}"
          category: "grype-golang"
          checkout_path: "./golang/"

      - name: Print directory
        run: |
          echo "Print directory"
          tree ./golang

      - name: Fail on any vulnerabilities
        if: steps.ScanSarifResult.outcome == 'failure'
        run: |
          echo "Vulnerabilities detected!"
          exit 1
