name: "Grype Scan"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  security-events: write

jobs:
  grype-scan:
    name: "Grype Scan"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Generate CycloneDX"
        uses: anchore/sbom-action@v0
        with:
          path: "."
          output-file: "grype-cyclonedx.json"
          format: "cyclonedx-json"
          artifact-name: "grype-cyclonedx.json"

      - name: "Generate SPDX"
        uses: anchore/sbom-action@v0
        with:
          path: "."
          output-file: "grype-spdx.json"
          format: "spdx-json"
          artifact-name: "grype-spdx.json"

      - name: Scan on PR
        if: github.event_name == 'pull_request'
        id: scan_result_pr
        uses: anchore/scan-action@v6
        with:
          sbom: "grype-cyclonedx.json"
          fail-build: true
          severity-cutoff: low
          output-format: table
          by-cve: true

      - name: Scan on main
        if: ${{ github.event_name != 'pull_request' }}
        id: scan_result
        uses: anchore/scan-action@v6
        continue-on-error: true
        with:
          sbom: "grype-cyclonedx.json"
          fail-build: true
          severity-cutoff: low
          output-format: sarif
          output-file: "grype.sarif"
          by-cve: true

      - name: "Scan on main: Upload result to GitHub Security tab"
        if: ${{ github.event_name != 'pull_request' }}
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: "${{ steps.scan_result.outputs.sarif }}"

      - name: "Scan on main: Fail on any vulnerabilities"
        if: github.event_name != 'pull_request' && steps.scan_result.outcome == 'failure'
        run: |
          echo "Vulnerabilities detected!"
          exit 1
