name: "Trivy Scan"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  security-events: write

jobs:
  trivy-scan:
    name: "Trivy Scan"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Manual Trivy Setup
        uses: aquasecurity/setup-trivy@v0.2.4
        with:
          cache: true
          version: v0.67.2

      - name: "Generate CycloneDX"
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          format: cyclonedx
          output: "trivy-cyclonedx.json"
          scan-ref: "."
          scanners: vuln,secret,misconfig,license
          skip-setup-trivy: true

      - name: "Upload CycloneDX"
        uses: actions/upload-artifact@v4
        with:
          name: "trivy-cyclonedx"
          path: "trivy-cyclonedx.json"

      - name: "Generate SPDX"
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          format: spdx-json
          output: "trivy-spdx.json"
          scan-ref: "."
          scanners: vuln,secret,misconfig,license
          skip-setup-trivy: true

      - name: "Upload SPDX"
        uses: actions/upload-artifact@v4
        with:
          name: "trivy-spdx"
          path: "trivy-spdx.json"

      - name: "Scan (print to console)"
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          format: "table"
          scan-ref: "."
          scanners: vuln,secret,misconfig,license
          skip-setup-trivy: true

      - name: "Scan"
        id: scan_result
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          scan-type: "fs"
          format: "sarif"
          output: "trivy.sarif"
          scan-ref: "."
          scanners: vuln,secret,misconfig,license
          exit-code: 1
          skip-setup-trivy: true

      - name: "Upload result to GitHub Security tab"
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: "trivy.sarif"

      - name: "Fail on any vulnerabilities"
        if: steps.scan_result.outcome == 'failure'
        run: |
          echo "Vulnerabilities detected!"
          exit 1
