name: "Trivy Scan: Golang"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  security-events: write

jobs:
  trivy-scan:
    name: "Trivy Scan"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Manual Trivy Setup
      #   uses: aquasecurity/setup-trivy@v0.2.4
      #   with:
      #     cache: true
      #     version: v0.67.2

      - name: "CycloneDX: Generate and scan"
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          format: cyclonedx
          output: "./golang/trivy-cyclonedx.json"
          scan-ref: "./golang/"
          scanners: vuln,secret,misconfig,license
          # skip-setup-trivy: true

      - name: "CycloneDX: Upload"
        uses: actions/upload-artifact@v4
        with:
          name: cyclonedx
          path: "./golang/trivy-cyclonedx.json"

      - name: "SPDX: Generate and scan"
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          format: spdx-json
          output: "./golang/trivy-spdx.json"
          scan-ref: "./golang/"
          scanners: vuln,secret,misconfig,license
          # skip-setup-trivy: true

      - name: "SPDX: Upload"
        uses: actions/upload-artifact@v4
        with:
          name: spdx
          path: "./golang/trivy-spdx.json"

      - name: "SARIF: Generate and scan"
        id: ScanSarifResult
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          scan-type: "fs"
          format: "sarif"
          output: "./golang/trivy-scan-results.sarif"
          scan-ref: "./golang/"
          scanners: vuln,secret,misconfig,license
          exit-code: 1
          # skip-setup-trivy: true

      - name: "SARIF: Upload"
        uses: actions/upload-artifact@v4
        with:
          name: sarif
          path: "./golang/trivy-scan-results.sarif"

      - name: "SARIF: Upload to GitHub Security tab"
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: "./golang/trivy-scan-results.sarif"
          category: "trivy-golang"
          # checkout_path: "./golang/"

      - name: Print directory
        run: |
          echo "Print directory"
          tree ./golang

      - name: Fail on any vulnerabilities
        if: steps.ScanSarifResult.outcome == 'failure'
        run: |
          echo "Vulnerabilities detected!"
          exit 1
