name: "Trivy Scan: Golang"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  security-events: write

env:
  TOOL: "trivy"
  PROJECT_DIR: "golang"

jobs:
  trivy-scan:
    name: "Trivy Scan"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Manual Trivy Setup
        uses: aquasecurity/setup-trivy@v0.2.4
        with:
          cache: true
          version: v0.67.2

      - name: "CycloneDX: Generate and scan"
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          format: cyclonedx
          output: "${{ github.workspace }}/${{ env.PROJECT_DIR }}/cyclonedx.json"
          scan-ref: "${{ github.workspace }}/${{ env.PROJECT_DIR }}"
          scanners: vuln,secret,misconfig,license
          skip-setup-trivy: true

      - name: "CycloneDX: Upload"
        uses: actions/upload-artifact@v4
        with:
          name: cyclonedx
          path: "${{ github.workspace }}/${{ env.PROJECT_DIR }}/cyclonedx.json"
          retention-days: 1

      - name: "SPDX: Generate and scan"
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          format: spdx-json
          output: "${{ github.workspace }}/${{ env.PROJECT_DIR }}/spdx.json"
          scan-ref: "${{ github.workspace }}/${{ env.PROJECT_DIR }}"
          scanners: vuln,secret,misconfig,license
          skip-setup-trivy: true

      - name: "SPDX: Upload"
        uses: actions/upload-artifact@v4
        with:
          name: spdx
          path: "${{ github.workspace }}/${{ env.PROJECT_DIR }}/spdx.json"
          retention-days: 1

      - name: "SARIF: Generate and scan"
        id: ScanSarifResult
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          scan-type: "fs"
          format: "sarif"
          output: "${{ github.workspace }}/${{ env.PROJECT_DIR }}/scan-results.sarif"
          scan-ref: "${{ github.workspace }}/${{ env.PROJECT_DIR }}"
          scanners: vuln,secret,misconfig,license
          skip-setup-trivy: true
          exit-code: 1

      - name: "SARIF: Upload"
        uses: actions/upload-artifact@v4
        with:
          name: sarif
          path: "${{ github.workspace }}/${{ env.PROJECT_DIR }}/scan-results.sarif"
          retention-days: 1

      - name: "SARIF: Upload to GitHub Security tab"
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: "${{ github.workspace }}/${{ env.PROJECT_DIR }}/scan-results.sarif"
          category: "${{ env.TOOL }}-${{ env.PROJECT_DIR }}"
          checkout_path: "${{ github.workspace }}/${{ env.PROJECT_DIR }}"

      - name: Fail on high severity vulnerabilities
        if: steps.ScanSarifResult.outcome == 'failure'
        run: |
          echo "High severity vulnerabilities detected!"
          exit 1
